language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      install:
        - composer update --no-interaction
    - php: '7.2'
      install:
        - composer update --no-interaction
    - php: '7.3'
    - php: '7.4'
    - php: '8.0'
    - php: 'nightly'
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer update --no-interaction --prefer-lowest
  allow_failures:
    - php: 'nightly'

env:
  global:
    - XDEBUG_MODE=coverage


addons:
   mariadb: '10.3'

before_install:
   - sudo mysql -e 'CREATE DATABASE passings_test'
   - sudo mysql -e 'GRANT ALL PRIVILEGES ON `passings_test`.* TO "php_test"@"localhost" IDENTIFIED BY "password";'
   - cp tests/test_config_db.php tests/config_db.php
   - sudo mysql passings_test < tests/test_data/passings.sql
   - sudo mysql passings_test < tests/test_data/transponders.sql
   - sudo mysql passings_test < tests/test_data/transponder_records.sql

install:
 - composer install --no-interaction

before_script:
 - vendor/bin/phpunit --version

script:
  - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)