name: PHP Composer

on:
  push:
    branches: [ master, actions-test ]
  pull_request:
    branches: [ master ]

jobs:
  version:
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    name: 'PHP version test'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0' ]
        os: [ ubuntu-latest, windows-latest ]
        db: [ mariadb, mysql ]

    steps:
      - name: Install MySQL
        if: ${{ runner.os == 'Windows' }}
        run: |
          choco install ${{ matrix.db }} --no-progress
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Install MariaDB
        if: ${{ runner.os == 'Linux' && matrix.db == mariadb }}
        run: |
          sudo apt-get install mariadb-server
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Start MySQL
        if: ${{ runner.os == 'Linux' }}
        run: sudo /etc/init.d/mysql start
      - name: Set up MySQL
        run: |
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: sockets, curl, gd, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup database
        run: php tests/setup.php

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  prefer_lowest:
    name: 'Prefer lowest dependency versions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          extensions: sockets, curl

      - name: Install dependencies
        run: composer update --prefer-lowest --no-progress

      - name: Setup MySQL
        run: |
          sudo systemctl start mysql.service
          php tests/setup.php

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1