name: PHP Composer
env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root

on:
  push:
    branches: [ master, actions-test ]
  pull_request:
    branches: [ master ]

jobs:
  version:
    name: 'PHP version test'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0' ]
        os: [ ubuntu-latest, windows-latest ]
        db: [ mariadb, mysql ]

    steps:
      - name: Install MySQL
        if: ${{ matrix.db == 'mysql' }}
        uses: ankane/setup-mysql@v1

      - name: Install MariaDB
        if: ${{ matrix.db == 'mariadb' }}
        uses: ankane/setup-mariadb@v1

      - name: Start MySQL
        if: ${{ runner.os == 'Linux' }}
        run: sudo /etc/init.d/mysql start

      - uses: actions/checkout@v2

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: sockets, curl, gd, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup database
        run: |
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          php tests/setup.php

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  prefer_lowest:
    name: 'Prefer lowest dependency versions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          extensions: sockets, curl, pdo_mysql

      - name: Install MariaDB
        uses: ankane/setup-mariadb@v1

      - name: Install dependencies
        run: composer update --prefer-lowest --no-progress

      - name: Setup database
        run: |
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          php tests/setup.php

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1