name: PHP Composer
env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  version:
    name: 'PHP version test'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.3', '7.4', '8.0', '8.1' ]
        os: [ ubuntu-latest, windows-latest ]
        db: [ mariadb, mysql ]
        exclude:
          - php: '7.3'
            db: mysql

    steps:
      - name: Install MySQL
        if: ${{ matrix.db == 'mysql' }}
        uses: ankane/setup-mysql@v1
        with:
          database: ${{ env.DB_DATABASE }}

      - name: Install MariaDB
        if: ${{ matrix.db == 'mariadb' }}
        uses: ankane/setup-mariadb@v1
        with:
          database: ${{ env.DB_DATABASE }}

      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: sockets, curl, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup database
        run: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  prefer_lowest:
    name: 'Prefer lowest dependency versions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: sockets, curl, pdo_mysql

      - name: Install MariaDB
        uses: ankane/setup-mariadb@v1
        with:
          database: ${{ env.DB_DATABASE }}

      - name: Install dependencies
        run: composer update --prefer-lowest --no-progress

      - name: Setup database
        run: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Run tests
        run: vendor/bin/phpunit